/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsSalaryGrowthRouteImport } from './routes/tools/salary-growth'
import { Route as ToolsInhandSalaryRouteImport } from './routes/tools/inhand-salary'
import { Route as ToolsBuyVsRentRouteImport } from './routes/tools/buy-vs-rent'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSalaryGrowthRoute = ToolsSalaryGrowthRouteImport.update({
  id: '/tools/salary-growth',
  path: '/tools/salary-growth',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsInhandSalaryRoute = ToolsInhandSalaryRouteImport.update({
  id: '/tools/inhand-salary',
  path: '/tools/inhand-salary',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsBuyVsRentRoute = ToolsBuyVsRentRouteImport.update({
  id: '/tools/buy-vs-rent',
  path: '/tools/buy-vs-rent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tools/buy-vs-rent': typeof ToolsBuyVsRentRoute
  '/tools/inhand-salary': typeof ToolsInhandSalaryRoute
  '/tools/salary-growth': typeof ToolsSalaryGrowthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tools/buy-vs-rent': typeof ToolsBuyVsRentRoute
  '/tools/inhand-salary': typeof ToolsInhandSalaryRoute
  '/tools/salary-growth': typeof ToolsSalaryGrowthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tools/buy-vs-rent': typeof ToolsBuyVsRentRoute
  '/tools/inhand-salary': typeof ToolsInhandSalaryRoute
  '/tools/salary-growth': typeof ToolsSalaryGrowthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tools/buy-vs-rent'
    | '/tools/inhand-salary'
    | '/tools/salary-growth'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/tools/buy-vs-rent'
    | '/tools/inhand-salary'
    | '/tools/salary-growth'
  id:
    | '__root__'
    | '/'
    | '/tools/buy-vs-rent'
    | '/tools/inhand-salary'
    | '/tools/salary-growth'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ToolsBuyVsRentRoute: typeof ToolsBuyVsRentRoute
  ToolsInhandSalaryRoute: typeof ToolsInhandSalaryRoute
  ToolsSalaryGrowthRoute: typeof ToolsSalaryGrowthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/salary-growth': {
      id: '/tools/salary-growth'
      path: '/tools/salary-growth'
      fullPath: '/tools/salary-growth'
      preLoaderRoute: typeof ToolsSalaryGrowthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/inhand-salary': {
      id: '/tools/inhand-salary'
      path: '/tools/inhand-salary'
      fullPath: '/tools/inhand-salary'
      preLoaderRoute: typeof ToolsInhandSalaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/buy-vs-rent': {
      id: '/tools/buy-vs-rent'
      path: '/tools/buy-vs-rent'
      fullPath: '/tools/buy-vs-rent'
      preLoaderRoute: typeof ToolsBuyVsRentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ToolsBuyVsRentRoute: ToolsBuyVsRentRoute,
  ToolsInhandSalaryRoute: ToolsInhandSalaryRoute,
  ToolsSalaryGrowthRoute: ToolsSalaryGrowthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
